services:
  db:
    image: mysql:8.0
    container_name: dalmoa-db
    restart: always
    environment:
      MYSQL_DATABASE: dalmoa
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: dalmoa-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      EXCHANGE_API_KEY: ${EXCHANGE_API_KEY}
    depends_on:
      - db
